name: tameika.lueilwitz
description: value-added
version: 0.0.1
author: sh1dwvyz.aiew8t6a@pk00proh.com
language: scala
buildSystem: ''
buildSystemDetails:
  artefactID: tameikalueilwitz
  parentArtefactID: ''
  buildSystem: maven
  author: null
  createdAt: '2024-10-24 21:52:57'
pipelines:
  pipelines/Miss_Annabel_KeelingMax_LittleAmbrose_Heller:
    name: Miss_Annabel_KeelingMax_LittleAmbrose_Heller
    description: null
    author: sh1dwvyz.aiew8t6a@pk00proh.com
    mode: batch
    artefactID: ''
    language: scala
    createdAt: '2024-10-24 21:52:57'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
datasets: {}
templates: {}
jobs: {}
gemContainer:
  languageVersion: 2.12.15
  gemLibsVersion: 1.1.26
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2024-10-24 21:52:57'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- modifiedAt: '2024-10-24T21:52:57.058756Z'
  name: plibMaven
  version: 8.4.0-SNAPSHOT
  id: '2121032579'
  createdAt: '2024-10-24T21:52:57.058756Z'
  type: plibMaven
projectDependencies: {}
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
